name: Robot Framework statuschecker CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.11]
        rf-version: [5.0.1, 6.0.2]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }} with Robot Framework ${{ matrix.rf-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies on Python
      if: matrix.python-version != 'pypy3'
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-dev.txt
        pip install robotframework==${{ matrix.rf-version }}
    - name: Install dependencies on pypy3
      if: matrix.python-version == 'pypy3'
      run: |
        python -m pip install --upgrade pip
        pip install robotframework==${{ matrix.rf-version }}
    - name: Run lint
      if: matrix.python-version != 'pypy3'
      run: |
        inv lint
    - name: Run tests
      run: |
        python --version
        python test/run.py
