name: Robot Framework statuschecker CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.9,  pypy3]
        rf-version: [3.2.2, 4.0.0]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }} with Robot Framework ${{ matrix.rf-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install robotframework==${{ matrix.rf-version }}
    - name: Run tests
      run: |
        python --version
        python test/run.py
