name: Robot Framework statuschecker CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.10.16, 3.12.8]
        rf-version: [6.1.1, 7.2]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }} with Robot Framework ${{ matrix.rf-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies on Python
      if: matrix.python-version != 'pypy3'
      run: |
        python -m pip install --upgrade pip uv
        uv pip install --python ${{ matrix.python-version }} --system -r requirements-dev.txt
        uv pip install --python ${{ matrix.python-version }} --system robotframework==${{ matrix.rf-version }}
    - name: Run lint
      run: |
        inv lint
      env:
        GITHUB_ACTIONS_RUNNIN_RUFF_LINT: 'true'
    - name: Run tests
      run: |
        python --version
        python test/run.py
